"""add owner

Revision ID: e668bc5a7e87
Revises: f684c19afb9d
Create Date: 2019-12-23 15:18:33.348276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e668bc5a7e87'
down_revision = 'f684c19afb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('cats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cats_id'], ['kittens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
